name: close_pr_store_comments_aws
on:
  issues:
    types:
      - closed
jobs:
  print-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print out comment
        run: |
          echo "Pull Request Id ${{github.event.pull_request.id}} for dummy pr"
