name: close_pr_store_comments_aws
on:
  pull_request:
    types:
      - merged
jobs:
  print-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print out comment
        run: |
          echo "El ID del pull request mergeado es: ${{ github.event.pull_request.id }} now let's try"
