name: CommentClassifier
on:
  pull_request_review_comment:
    types:
      - created

jobs:
  print-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print out comment
        run: |
          echo "Comment ${{github.event.comment.body}} using pull_request_review_comment"
