name: CommentClassifier
on:
  pull_request_review:
    types:
      - submitted

jobs:
  print-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print out comment
        run: |
          echo "Comment ${{github.event.review}} using pull_request_review"
